Tools - fix php deprecation in security checker
https://github.com/EdgedesignCZ/phpqa/actions/runs/15661571066/job/44120076655?pr=265#step:7:355
ERROR: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in SecurityChecker.php:18